services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - data_db:/var/lib/mysql
      - ./databaseistitutoperprove.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  server:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:ro
      - ./sites/default/images:/var/www/html/sites/default/images
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=databaseistitutoperprove

volumes:
  data_db:
